In [1]:
# You are given a dataset of fake and clean currency notes. The problem is to find if the given currency note is fake or clean.
# Prepare the data and create models using all the decision tree techniques such as CART, C4.5 and ID3 and 
# find the best of all your models. Use python to create the model and cross-validate the dataset. 
# Please make sure you also use appropriate performance measures, error values, bias and variance to come to conclusion 
# of the best dataset


# Use: 
# Model:          Classification using Decision Trees
# Algorithm:      CART, C4.5 and ID3


import pandas as pd
import numpy as np


from sklearn.cross_validation import train_test_split # cross-validate the dataset. 
from sklearn import tree     # Import decision tree classifiler algorithm, its supervised learing algorithm


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


# Load Dataset

In [2]:
df = pd.read_csv('D:/AIML-L2/BankNote_Authentication_Q2.csv')
df.head()

VarianceWTrans_image  SkewnessWTrans_image  CurtosisWTrans_image  \
0               3.62160                8.1674               -2.8073   
1               4.54590               -2.6383               -2.4586   
2               3.86600                9.5228                1.9242   
3               3.45660               -4.4552               -4.0112   
4               0.32924                9.6718                4.5718   

   Entropy_image  Class  
0       -0.44699      0  
1       -1.46210      0  
2        0.10645      0  
3       -3.59440      0  
4       -0.98880      0

# Data prepration

In [3]:
df.isnull().sum()

VarianceWTrans_image    0
SkewnessWTrans_image    0
CurtosisWTrans_image    0
Entropy_image           0
Class                   0
dtype: int64

In [4]:
#  Find the naull values in column SkewnessWTrans_image
df.isnull().any(axis=1)   # on index where is True that row has NaN values



0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
        ...  
1342    False
1343    False
1344    False
1345    False
1346    False
1347    False
1348    False
1349    False
1350    False
1351    False
1352    False
1353    False
1354    False
1355    False
1356    False
1357    False
1358    False
1359    False
1360    False
1361    False
1362    False
1363    False
1364    False
1365    False
1366    False
1367    False
1368    False
1369    False
1370    False
1371    False
Length: 1372, dtype: bool

In [5]:
df['SkewnessWTrans_image'] # check the one column values


0        8.16740
1       -2.63830
2        9.52280
3       -4.45520
4        9.67180
5        3.01290
6       -6.81000
7        5.75880
8        9.17720
9        8.77790
10      -2.70660
11       7.66250
12      10.84300
13       8.72610
14      -3.38950
15       1.93520
16       2.84730
17      -4.87940
18      11.02720
19       7.89020
20      -4.45520
21       1.93520
22       8.88550
23       9.88700
24      -5.49810
25      -3.74130
26       8.39090
27       9.81870
28      -3.35840
29      -0.17797
          ...   
1342    -6.71280
1343     0.23589
1344     4.09510
1345     4.87310
1346     9.12140
1347     2.34450
1348    -2.15620
1349    -2.20380
1350     1.90170
1351     3.42880
1352     3.22190
1353     3.35640
1354     8.70960
1355     2.92390
1356     1.93520
1357    -0.19038
1358     2.49140
1359     1.93680
1360     1.06360
1361     1.59330
1362    -1.42370
1363    -6.63000
1364    -5.81260
1365     3.74330
1366     1.34920
1367    -4.87730
1368   -13.45860
1369    -8.382

In [6]:
 # get correct row number fro NaN values from column
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [VarianceWTrans_image, SkewnessWTrans_image, CurtosisWTrans_image, Entropy_image, Class]
Index: []

In [7]:
# check for NaN values
pd.isnull(df)

VarianceWTrans_image  SkewnessWTrans_image  CurtosisWTrans_image  \
0                    False                 False                 False   
1                    False                 False                 False   
2                    False                 False                 False   
3                    False                 False                 False   
4                    False                 False                 False   
5                    False                 False                 False   
6                    False                 False                 False   
7                    False                 False                 False   
8                    False                 False                 False   
9                    False                 False                 False   
10                   False                 False                 False   
11                   False                 False                 False   
12                   False                 False                 False   
13                   False                 False                 False   
14                   False                 False                 False   
15                   False                 False                 False   
16                   False                 False                 False   
17                   False                 False                 False   
18                   False                 False                 False   
19                   False                 False                 False   
20                   False                 False                 False   
21                   False                 False                 False   
22                   False                 False                 False   
23                   False                 False                 False   
24                   False                 False                 False   
25                   False                 False                 False   
26                   False                 False                 False   
27                   False                 False                 False   
28                   False                 False                 False   
29                   False                 False                 False   
...                    ...                   ...                   ...   
1342                 False                 False                 False   
1343                 False                 False                 False   
1344                 False                 False                 False   
1345                 False                 False                 False   
1346                 False                 False                 False   
1347                 False                 False                 False   
1348                 False                 False                 False   
1349                 False                 False                 False   
1350                 False                 False                 False   
1351                 False                 False                 False   
1352                 False                 False                 False   
1353                 False                 False                 False   
1354                 False                 False                 False   
1355                 False                 False                 False   
1356                 False                 False                 False   
1357                 False                 False                 False   
1358                 False                 False                 False   
1359                 False                 False                 False   
1360                 False                 False                 False   
1361                 False                 False                 False   
1362                 False                 False                 False   
1363                 False                 False                 False   
1364      

In [8]:
# CFill the null values in column
df['SkewnessWTrans_image'].fillna('0', inplace = True)

In [9]:
# Check the null values is replaced as 0
df['SkewnessWTrans_image']
#df[df.isnull().any(axis=1)]

0        8.16740
1       -2.63830
2        9.52280
3       -4.45520
4        9.67180
5        3.01290
6       -6.81000
7        5.75880
8        9.17720
9        8.77790
10      -2.70660
11       7.66250
12      10.84300
13       8.72610
14      -3.38950
15       1.93520
16       2.84730
17      -4.87940
18      11.02720
19       7.89020
20      -4.45520
21       1.93520
22       8.88550
23       9.88700
24      -5.49810
25      -3.74130
26       8.39090
27       9.81870
28      -3.35840
29      -0.17797
          ...   
1342    -6.71280
1343     0.23589
1344     4.09510
1345     4.87310
1346     9.12140
1347     2.34450
1348    -2.15620
1349    -2.20380
1350     1.90170
1351     3.42880
1352     3.22190
1353     3.35640
1354     8.70960
1355     2.92390
1356     1.93520
1357    -0.19038
1358     2.49140
1359     1.93680
1360     1.06360
1361     1.59330
1362    -1.42370
1363    -6.63000
1364    -5.81260
1365     3.74330
1366     1.34920
1367    -4.87730
1368   -13.45860
1369    -8.382

In [10]:
df.std()

VarianceWTrans_image    2.842763
SkewnessWTrans_image    5.841005
CurtosisWTrans_image    4.255792
Entropy_image           2.097848
Class                   0.497103
dtype: float64

In [11]:
df.dtypes

VarianceWTrans_image    float64
SkewnessWTrans_image    float64
CurtosisWTrans_image    float64
Entropy_image           float64
Class                     int64
dtype: object

In [12]:
df.shape

(1372, 5)

In [13]:
df.describe()

VarianceWTrans_image  SkewnessWTrans_image  CurtosisWTrans_image  \
count           1372.000000           1372.000000           1372.000000   
mean               0.433735              1.935223              1.379224   
std                2.842763              5.841005              4.255792   
min               -7.042100            -13.773100             -5.286100   
25%               -1.773000             -1.604225             -1.543700   
50%                0.496180              2.277250              0.671900   
75%                2.821475              6.804300              3.099525   
max                6.824800             12.951600             17.927400   

       Entropy_image        Class  
count    1372.000000  1372.000000  
mean       -1.180210     0.444606  
std         2.097848     0.497103  
min        -8.548200     0.000000  
25%        -2.397300     0.000000  
50%        -0.580830     0.000000  
75%         0.400305     1.000000  
max         2.449500     1.000000

In [14]:
# Find the features and target variable

x = np.array(df.drop(['Class'], axis = 1))
y = np.array(df['Class'])

In [15]:
x.shape

(1372, 4)

In [16]:
y.shape

(1372,)

# Cross-validate the dataset

In [17]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=20)

In [18]:
x_test

array([[ 3.8197 ,  1.8127 , -4.383  , -4.0327 ],
       [ 4.1038 ,  8.7903 ,  3.3491 , -0.49225],
       [ 2.9736 , -3.3109 , -3.6359 , -1.3754 ],
       ...,
       [-2.5724 , -6.0816 ,  2.7073 , -0.16639],
       [ 2.6719 ,  2.8473 ,  0.37158,  0.58619],
       [ 2.7206 ,  8.6889 , -3.3111 , -0.96811]])

In [19]:
y_test

array([0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,

In [20]:
x_train

array([[ 3.5251  , -5.4236  ,  1.6928  ,  0.64438 ],
       [ 3.7818  ,  1.3098  ,  2.2558  , -0.15734 ],
       [ 1.5902  ,  5.1939  ,  3.2403  ,  0.18404 ],
       ...,
       [-4.4775  , -8.1819  , 17.0834  , -3.0345  ],
       [ 5.3915  , -0.070365, -3.8081  , -3.3642  ],
       [ 2.5817  ,  0.23175 , -3.1749  , -2.9957  ]])

In [21]:
y_train

array([0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,

# 	Data Modelling


In [22]:
# Create your model

model = tree.DecisionTreeClassifier()


# Train your dataset using fit method

In [23]:
model.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [24]:
#np.reshape(df, (2, 3))

# Model Evaluation

In [25]:
#pred= model.predict(x_test)
pred= model.predict(y_test, 1)
pred

ValueError: Expected 2D array, got 1D array instead:
array=[0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0.
 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 1. 0. 1. 1. 0. 1. 0. 0.
 1. 0. 0. 1. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1.
 0. 1. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 0. 0. 1.
 1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 0. 1.
 1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 1. 1. 0. 1. 1. 0. 1. 0. 0. 1. 0. 0. 1. 0.
 0. 1. 1. 0. 0. 0. 1. 1. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 1. 0.
 1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1.
 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 1. 0. 1. 1. 0. 0. 0. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 0. 1. 1. 0. 0. 1.
 1. 0. 0. 1. 1. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 0. 1. 0. 1.
 0. 0. 0. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0.
 1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 1. 1. 0.
 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1.
 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1.
 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0.
 0. 1. 1. 0. 0. 1. 0. 1. 1. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1. 0. 0.
 0. 1. 0. 0.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

# Checking with ID3

In [26]:
# Testing
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

#from tensorflow.keras.models import Sequential

In [27]:
def plotPerColumnDistribution(df, nGraphShown, nGraphPerRow):
    nunique = df.nunique()
    df = df[[col for col in df if nunique[col] > 1 and nunique[col] < 50]]

In [28]:
plotPerColumnDistribution(df, 10, 5)

In [ ]:
# Testing with other ML algoritm

# Using RandomForest

In [ ]:
from sklearn.ensemble import RandomForestClassifier


In [ ]:
Clf = RandomForestClassifier(n_estimators=100, max_depth=2, random_state=0)

In [ ]:
#Clf.fit(x_train, y_train)

# LabelEndcoder

In [ ]:
from sklearn import preprocessing

In [ ]:
le = preprocessing.LabelEncoder()

In [ ]:
le.fit(['x_train', 'y_train'])

In [ ]:
list(le.classes_)

In [ ]:
le.transform(['x_train', 'y_train'])

In [ ]:
le.fit(['x_train'])

In [ ]:
le.fit(['y_train'])

In [ ]:
#p = le.Predict('y_train')