In [55]:
#Import relevant python libraries and sklearn KNN model  
import pandas as pd
import numpy as np
from sklearn import cross_validation, neighbors # for KNN
from sklearn import linear_model # For KNN
from sklearn.linear_model import LinearRegression # for predict the model

In [56]:
#Read the data base
data = pd.read_csv('E:/ML/AI ML docs/Haberman.csv')

In [57]:
#Identify target variable and independent variable. 1. Traget variable is Survival_status and other is fetures variable
data.head(8)

Age_patient  Patient's_year  Number_positive  Survival_status
0           30              64                1                1
1           30              62                3                1
2           30              65                0                1
3           31              59                2                1
4           31              65                4                1
5           33              58               10                1
6           33              60                0                1
7           34              59                0                2

In [58]:
#x = np.array(data.drop(['Patients_year'],1))
# Target var is Survaival status
y=np.array(data['Survival_status'])

In [59]:
y

array([1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1,
       1, 2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2,
       2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1,
       1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1,
       1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2,
       2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1,

In [115]:
# feture variables are Age_patient, Patient's_year,Number_positive
x=np.array(data.drop(['Survival_status'],1))

AttributeError: 'LinearRegression' object has no attribute 'drop'

In [116]:
x

array([[30, 64,  1],
       [30, 62,  3],
       [30, 65,  0],
       [31, 59,  2],
       [31, 65,  4],
       [33, 58, 10],
       [33, 60,  0],
       [34, 59,  0],
       [34, 66,  9],
       [34, 58, 30],
       [34, 60,  1],
       [34, 61, 10],
       [34, 67,  7],
       [34, 60,  0],
       [35, 64, 13],
       [35, 63,  0],
       [36, 60,  1],
       [36, 69,  0],
       [37, 60,  0],
       [37, 63,  0],
       [37, 58,  0],
       [37, 59,  6],
       [37, 60, 15],
       [37, 63,  0],
       [38, 69, 21],
       [38, 59,  2],
       [38, 60,  0],
       [38, 60,  0],
       [38, 62,  3],
       [38, 64,  1],
       [38, 66,  0],
       [38, 66, 11],
       [38, 60,  1],
       [38, 67,  5],
       [39, 66,  0],
       [39, 63,  0],
       [39, 67,  0],
       [39, 58,  0],
       [39, 59,  2],
       [39, 63,  4],
       [40, 58,  2],
       [40, 58,  0],
       [40, 65,  0],
       [41, 60, 23],
       [41, 64,  0],
       [41, 67,  0],
       [41, 58,  0],
       [41, 5

In [117]:
# shape the model
print(x.shape,y.shape)

(306, 3) (306,)


In [118]:
#Split the file into train [80%] and test [20%] data 
x_train, x_test, y_train,y_test = cross_validation.train_test_split(x,y,test_size=0.20)

In [119]:
# Apply KNN algorithm 
KNN = neighbors.KNeighborsClassifier()

In [122]:
#data = linear_model.LinearRegression()

In [123]:
# fit the x and y
KNN.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [124]:
## Perform Accuracy check on test dataset
acc = KNN.score(x_train, y_train)

In [125]:
acc

0.7909836065573771

In [127]:
# Predict using test data
#x_pred = data.predict(x_train)
data=linear_model.LinearRegression()

In [128]:
data.fit(x_test, y_test)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [129]:
x_pred = data.predict(x_test)

In [130]:
x_pred

array([1.31721207, 1.22626632, 1.75894853, 1.27287763, 1.52727644,
       1.40534985, 1.30013754, 1.64342588, 1.30278931, 1.27097762,
       1.26025918, 1.43703459, 1.32129326, 1.26885893, 1.27069646,
       1.86629615, 1.2730026 , 1.35905292, 1.30261649, 1.34845944,
       1.23486607, 1.25384061, 1.26868611, 1.66455036, 1.26234664,
       1.48742932, 1.33606165, 1.3085186 , 1.42655144, 1.75916919,
       1.29643322, 1.26868611, 1.23059743, 1.28945034, 1.38869806,
       1.72097018, 1.30260186, 1.27512129, 1.26652155, 1.30428121,
       1.35914664, 1.21159165, 1.8202179 , 1.33612413, 1.4393261 ,
       2.55199611, 1.27917124, 1.23277861, 1.25393433, 1.22636004,
       1.23069116, 1.27708379, 1.25377813, 1.29401675, 1.30911415,
       1.84118618, 1.32314542, 1.41600581, 1.33386386, 1.39492918,
       1.25175315, 1.2855732 ])

In [131]:
# Perform Accuracy check on test dataset
KNN.fit(x_test, y_test)
accuracy = KNN.score(x_test, y_test)

In [132]:
accuracy

0.7580645161290323